- name: ðŸ“¦ Install dependencies (Dev)
  if: ${{ inputs.env == 'dev' }}
  run: |
    pip install -r requirements.txt
    pip install -r requirements-dev.txt
    pip install -r models/requirements-ai.txt

- name: ðŸ“¦ Install dependencies (Prod)
  if: ${{ inputs.env == 'prod' }}
  run: |
    pip install -r requirements.txt
    pip install -r models/requirements-ai.txt

- name: ðŸ“¦ Install dependencies (CI/CD)
  if: ${{ inputs.env == 'ci' }}
  run: |
    pip install -r requirements.txt
    pip install -r requirements-dev.txt
    pip install -r models/requirements-ai.txt
    pip install torch==2.9.1+cpu --index-url https://download.pytorch.org/whl/cpu